'use client';
import {useEffect,useRef,useState} from 'react';
import {KeyRound,Mail,ShieldCheck,Plus,Search,X,UserRound,Settings,LockKeyhole} from 'lucide-react';
type Profile={id:string;username:string;role:string;email:string|null;emailVerifiedAt:number|null;revision:number};
type User=Profile&{active:number;createdAt:number};
async function request(path:string,body?:unknown){const r=await fetch(path,{cache:'no-store',...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const data:any=await r.json();if(!r.ok)throw new Error(data.error??'No se pudo completar la operación.');return data;}
function Toast({message,onClose}:{message:string;onClose:()=>void}){useEffect(()=>{if(!message)return;const id=setTimeout(onClose,3000);return()=>clearTimeout(id);},[message]);return message?<div className="admin-notice" role="status"><span>{message}</span><button className="icon-button" aria-label="Cerrar notificación" onClick={onClose}><X size={17}/></button></div>:null;}
export function AccountPanel(){
 const [data,setData]=useState<{user:Profile;emailEnabled:boolean}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[current,setCurrent]=useState(''),[newPassword,setNew]=useState(''),[confirmation,setConfirmation]=useState(''),[emailPassword,setEmailPassword]=useState('');
 const lock=useRef(false);
 async function load(){try{const d=await request('/api/account');setData(d);setEmail(d.user.email??'');setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function send(path:string,body:unknown){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const d=await request(path,body);if(d.reauthenticate){window.location.assign('/login');return;}setNotice(d.message??'Cambios guardados.');setEmailPassword('');await load();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 return <section className="account-panel"><div className="page-heading"><div><span className="eyebrow">ACCESO · CONFIGURACIÓN PERSONAL</span><h1>Mi cuenta.</h1><p>Gestiona tu contraseña y el correo para recuperar tu acceso.</p></div></div>
  {error&&<div className="error-banner" role="alert">{error}<button disabled={busy} onClick={()=>void load()}>Actualizar</button></div>}<Toast message={notice} onClose={()=>setNotice('')}/>
  {data?<><div className="account-identity"><UserRound size={25}/><div><strong>{data.user.username}</strong><span>{data.user.role==='admin'?'Administrador':'Equipo · pedidos y caja'}</span></div></div>
   <div className="account-columns"><form className="account-card" onSubmit={e=>{e.preventDefault();void send('/api/account',{type:'password',currentPassword:current,password:newPassword,confirmation});}}><div className="account-card-title"><KeyRound size={24}/><h2>Cambiar contraseña</h2></div>
    <label className="field"><span>Contraseña actual</span><input type="password" autoComplete="current-password" required maxLength={256} disabled={busy} value={current} onChange={e=>setCurrent(e.target.value)}/></label>
    <label className="field"><span>Nueva contraseña</span><input type="password" autoComplete="new-password" minLength={8} maxLength={256} required disabled={busy} value={newPassword} onChange={e=>setNew(e.target.value)}/></label>
    <label className="field"><span>Confirmar nueva contraseña</span><input type="password" autoComplete="new-password" minLength={8} maxLength={256} required disabled={busy} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>
    <p className="helper">Usa al menos 8 caracteres. Al cambiarla se cerrarán todas tus sesiones y volverás a iniciar sesión.</p><button className="primary full" disabled={busy}>{busy?'Guardando…':'Guardar nueva contraseña'}</button>
   </form><div className="account-card"><div className="account-card-title"><Mail size={24}/><h2>Correo de recuperación</h2></div><span className={'account-email-status '+(data.user.emailVerifiedAt?'verified':'')}><ShieldCheck size={17}/>{data.user.emailVerifiedAt?'Correo verificado':data.user.email?'Sin verificar':'Sin correo asociado'}</span>
    <form onSubmit={e=>{e.preventDefault();void send('/api/account',{type:'email',email:email.trim(),revision:data.user.revision,currentPassword:emailPassword});}}><label className="field"><span>Correo real para recibir mensajes</span><input type="email" autoComplete="email" maxLength={254} disabled={busy} placeholder="nombre@gmail.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>Contraseña actual para guardar el correo</span><input type="password" autoComplete="current-password" required maxLength={256} disabled={busy} value={emailPassword} onChange={e=>setEmailPassword(e.target.value)}/></label><p className="helper">Tu usuario de ingreso se mantiene. Si cambias el correo, tendrás que verificarlo nuevamente.</p><button className="primary full" disabled={busy}>Guardar correo</button></form>
    <div className="email-verification"><button className="secondary full" disabled={busy||!data.user.email||!!data.user.emailVerifiedAt||!data.emailEnabled} onClick={()=>void send('/api/auth/email',{type:'request'})}>Enviar verificación de correo</button>{!data.emailEnabled?<p className="email-pending"><strong>Envío de correos pendiente de configurar.</strong> Mientras tanto, puedes cambiar tu contraseña aquí. El administrador también puede restablecer el acceso del equipo.</p>:<p className="helper">Recibirás un enlace válido por 30 minutos. Revisa también la carpeta de spam.</p>}</div>
   </div></div></>:!error&&<p role="status">Cargando tu cuenta…</p>}
 </section>;
}
type Modal={type:'create'|'update'|'status'|'password';user?:User};
export function UsersPanel(){
 const [users,setUsers]=useState<User[]>([]),[self,setSelf]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('Activos'),[busy,setBusy]=useState(false),[modal,setModal]=useState<Modal|null>(null),[formError,setFormError]=useState('');
 const [username,setUsername]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('operator'),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[adminPassword,setAdminPassword]=useState(''),[createId,setCreateId]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),lock=useRef(false);
 async function load(){try{const d=await request('/api/users');setUsers(d.users);setSelf(d.selfId);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);useEffect(()=>{if(modal)dialog.current?.showModal();},[modal]);
 function open(type:Modal['type'],user?:User){setUsername(user?.username??'');setEmail(user?.email??'');setRole(user?.role??'operator');setPassword('');setConfirmation('');setAdminPassword('');setFormError('');setCreateId(crypto.randomUUID());setModal({type,user});}
 function close(){if(!lock.current){setModal(null);setPassword('');setConfirmation('');setAdminPassword('');}}
 async function save(){if(!modal||lock.current)return;lock.current=true;setBusy(true);setFormError('');
  try{const a={type:modal.type,id:modal.user?.id??createId,revision:modal.user?.revision,username,email:email.trim(),role,password,confirmation,adminPassword,active:!modal.user?.active};const d=await request('/api/users',a);setUsers(d.users);setSelf(d.selfId);setModal(null);setPassword('');setConfirmation('');setAdminPassword('');setNotice(modal.type==='create'?'Usuario creado.':modal.type==='password'?'Contraseña restablecida. Las sesiones anteriores de ese usuario ya no permiten entrar.':'Usuario actualizado.');}
  catch(e){setFormError((e as Error).message);}finally{lock.current=false;setBusy(false);}
 }
 const visible=users.filter(u=>(status==='Todos'||(status==='Activos'?!!u.active:!u.active))&&(u.username.toLowerCase().includes(query.toLowerCase())||(u.email??'').toLowerCase().includes(query.toLowerCase())));
 return <section className="users-panel"><div className="page-heading"><div><span className="eyebrow">ADMINISTRACIÓN · ACCESOS DEL EQUIPO</span><h1>Usuarios.</h1><p>Crea accesos, asigna permisos y restablece contraseñas.</p></div><button className="primary" disabled={loading||busy} onClick={()=>open('create')}><Plus size={19}/>Nuevo usuario</button></div>
  <div className="admin-info"><LockKeyhole size={23}/><p><strong>Las contraseñas guardadas no se muestran.</strong><span>Para cambiar una contraseña, define una nueva. Las sesiones anteriores se invalidan al restablecerla, cambiar permisos o desactivar un usuario. Tu propio acceso se gestiona en «Mi cuenta».</span></p></div>
  {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>void load()}>Actualizar lista</button></div>}<Toast message={notice} onClose={()=>setNotice('')}/>
  <div className="admin-filters"><label className="search"><Search size={18}/><input aria-label="Buscar usuarios" placeholder="Buscar usuario o correo" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="field"><span>Estado de usuario</span><select value={status} onChange={e=>setStatus(e.target.value)}>{['Activos','Inactivos','Todos'].map(v=><option key={v}>{v}</option>)}</select></label><button className="secondary" onClick={()=>void load()} disabled={busy}>Actualizar lista</button></div>
  <div className="user-list">{visible.map(u=><article className={'account-card user-card '+(!u.active?'inactive':'')} key={u.id}><div className="user-card-heading"><UserRound size={23}/><div><h2>{u.username}</h2><span>{u.role==='admin'?'Administrador':'Equipo · pedidos y caja'}{u.id===self?' · Tu cuenta':''}</span></div><b className="admin-state">{u.active?'Activo':'Inactivo'}</b></div><p className="user-email">{u.email??'Sin correo real asociado'} <span>{u.emailVerifiedAt?'Verificado':u.email?'Sin verificar':''}</span></p>
   {u.id!==self?<div className="user-actions"><button className="secondary" disabled={busy} onClick={()=>open('update',u)}><Settings size={16}/>Editar acceso</button><button className="secondary" disabled={busy} onClick={()=>open('password',u)}><KeyRound size={16}/>Restablecer contraseña</button><button className="text-button" disabled={busy} onClick={()=>open('status',u)}>{u.active?'Desactivar':'Activar'}</button></div>:<p className="helper">Cambia tu contraseña y tu correo desde «Mi cuenta».</p>}
  </article>)}</div>{loading&&<p role="status">Cargando usuarios…</p>}{!loading&&!visible.length&&!error&&<p className="empty">No hay usuarios con esos filtros.</p>}
  {modal&&<dialog ref={dialog} aria-label="Gestionar usuario" onCancel={e=>{if(busy)e.preventDefault();else close();}}><header className="dialog-head"><div><span className="eyebrow">LUCIANOS · ADMINISTRACIÓN</span><h2>{modal.type==='create'?'Nuevo usuario':modal.type==='password'?'Restablecer contraseña':modal.type==='status'?(modal.user?.active?'Desactivar usuario':'Activar usuario'):'Editar acceso'}</h2></div><button className="icon-button" disabled={busy} onClick={close} aria-label="Cerrar formulario de usuario"><X size={20}/></button></header>
   <form onSubmit={e=>{e.preventDefault();void save();}}><div className="dialog-body">{modal.user&&<p className="user-target">{modal.user.username}</p>}
    {(modal.type==='create'||modal.type==='update')&&<><label className="field"><span>Usuario de ingreso</span><input autoComplete="off" required minLength={3} maxLength={120} disabled={busy} value={username} onChange={e=>setUsername(e.target.value)} placeholder="Ej. encargado@sistema.com"/></label><label className="field"><span>Rol del usuario</span><select disabled={busy} value={role} onChange={e=>setRole(e.target.value)}><option value="operator">Equipo · pedidos y caja</option><option value="admin">Administrador · carta y usuarios</option></select></label><label className="field"><span>Correo real de recuperación (opcional)</span><input type="email" maxLength={254} disabled={busy} value={email} onChange={e=>setEmail(e.target.value)} placeholder="nombre@gmail.com"/></label><p className="helper">El usuario de ingreso puede ser ficticio. Para verificar o recuperar el acceso se necesita un correo real.</p></>}
    {(modal.type==='create'||modal.type==='password')&&<><label className="field"><span>{modal.type==='create'?'Contraseña inicial':'Nueva contraseña del usuario'}</span><input type="password" autoComplete="new-password" required minLength={8} maxLength={256} disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field"><span>Confirmar contraseña del usuario</span><input type="password" autoComplete="new-password" required minLength={8} maxLength={256} disabled={busy} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label></>}
    {modal.type==='status'&&<p>{modal.user?.active?'El usuario perderá acceso inmediatamente. Puedes volver a activarlo después. Sus pedidos y registros se conservan.':'El usuario podrá volver a entrar con su contraseña actual.'}</p>}
    <label className="field"><span>Tu contraseña de administrador para confirmar</span><input type="password" autoComplete="current-password" required maxLength={256} disabled={busy} value={adminPassword} onChange={e=>setAdminPassword(e.target.value)}/></label>{formError&&<p className="error-banner" role="alert">{formError}<button type="button" onClick={()=>{close();void load();}} disabled={busy}>Actualizar lista</button></p>}
   </div><div className="dialog-foot"><button type="button" className="text-button" disabled={busy} onClick={close}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Confirmar cambios'}</button></div></form>
  </dialog>}
 </section>;
}
