'use client';
import {useEffect,useRef,useState} from 'react';
import {PackagePlus,RefreshCw,X,Search,Package} from 'lucide-react';
import type {ManagedProduct} from '@/lib/catalog-model';
import type {Inventory} from '@/lib/inventory';
type Movement={id:string;product_id:string;delta:number;remaining:number;reason:string;actor:string;at:string;name:string};
type Data=Inventory&{products:ManagedProduct[];movements:Movement[]};
type Draft={product:ManagedProduct;type:string;qty:string;reason:string;revision:number;opId:string};
export default function InventoryPanel({onChanged}:{onChanged:()=>void}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[product,setProduct]=useState(''),[query,setQuery]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[date,setDate]=useState(''),[more,setMore]=useState(true);
 const dialog=useRef<HTMLDialogElement>(null),lock=useRef(false),sequence=useRef(0),operation=useRef<Draft|null>(null);
 async function load(older=false){const seq=++sequence.current;try{const params=new URLSearchParams({product,date});if(older&&data?.movements.length){params.set('before',data.movements.at(-1)!.at);params.set('beforeId',data.movements.at(-1)!.id);}const r=await fetch('/api/inventory?'+params,{cache:'no-store'});const s:any=await r.json();if(!r.ok)throw new Error(s.error);if(seq===sequence.current){setData(old=>older&&old?{...s,movements:[...old.movements,...s.movements]}:s);setMore(s.movements.length===100);setError('');}}catch(e){if(seq===sequence.current)setError((e as Error).message);}}
 useEffect(()=>{void load();const interval=setInterval(()=>{if(!lock.current&&!dialog.current?.open&&!date)void load();},12000);return()=>{sequence.current++;clearInterval(interval);};},[product,date]);
 useEffect(()=>{if(draft)dialog.current?.showModal();},[draft]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(id);},[notice]);
 function open(p:ManagedProduct){operation.current=null;setDraft({product:p,type:data?.quantities[p.id]==null?'initial':'restock',qty:'',reason:'',revision:data!.revision,opId:crypto.randomUUID()});setError('');}
 async function save(){if(!draft||lock.current)return;lock.current=true;setBusy(true);sequence.current++;const a=operation.current&&JSON.stringify({...draft,opId:''})===JSON.stringify({...operation.current,opId:''})?operation.current:{...draft,opId:crypto.randomUUID()};operation.current=a;
  try{const r=await fetch('/api/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...a,productId:a.product.id,qty:Number(a.qty)})});const s:any=await r.json();if(s.quantities)setData(s);if(!r.ok){if(r.status<500)operation.current=null;throw new Error(s.error);}operation.current=null;setDraft(null);setNotice('Inventario guardado. El saldo se conservará para las próximas jornadas.');onChanged();setError('');void load();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}
 }
 const visible=data?.products.filter(p=>p.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()))??[];
 return <section className="inventory-panel"><div className="page-heading"><div><span className="eyebrow">BEBIDAS · STOCK DEL NEGOCIO</span><h1>Siempre a la mano.</h1><p>Gaseosas disponibles entre domingos, lunes y jueves.</p></div><button className="secondary" disabled={busy} onClick={()=>void load()}><RefreshCw size={18}/>Actualizar</button></div>
  <div className="admin-info"><Package size={24}/><p><strong>El stock se descuenta al registrar el pedido.</strong><span>Editar cantidades o anular un pedido devuelve las unidades correspondientes. Cerrar la jornada conserva el saldo. Las jarras frescas y cervezas se gestionan en la carta del día.</span></p></div>
  {error&&!draft&&<div className="error-banner" role="alert">{error}<button onClick={()=>void load()}>Reintentar</button></div>}{notice&&<div className="admin-notice" role="status">{notice}</div>}
  <label className="search"><Search size={18}/><input aria-label="Buscar gaseosa" placeholder="Buscar gaseosa" value={query} onChange={e=>setQuery(e.target.value)}/></label>
  <div className="inventory-grid">{visible.map(p=>{const qty=data!.quantities[p.id]??null;return <article className={'inventory-card '+(qty===0?'empty-stock':'')} key={p.id}><span className="eyebrow">{!p.active?'RETIRADA DE LA CARTA':'GASEOSA'}</span><h3>{p.name}</h3><div className="inventory-quantity"><strong>{qty===null?'—':qty}</strong><span>{qty===null?'Stock inicial pendiente':qty===0?'Agotada':'unidades disponibles'}</span></div><button className="secondary full" onClick={()=>open(p)}><PackagePlus size={18}/>{qty===null?'Registrar stock inicial':'Reponer / ajustar'}</button></article>;})}</div>
  {!data&&!error&&<p>Cargando inventario…</p>}
  <div className="section-heading"><h2>Movimiento de bebidas</h2></div><div className="inventory-filters"><label className="field"><span>Gaseosa</span><select value={product} onChange={e=>setProduct(e.target.value)}><option value="">Todas</option>{data?.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field"><span>Fecha del movimiento</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="text-button" onClick={()=>setDate('')}>Todas las fechas</button></div>
  <div className="report-table-wrap"><table className="report-table"><thead><tr><th>Fecha / gaseosa</th><th>Movimiento</th><th>Unidades</th><th>Quedaron</th></tr></thead><tbody>{data?.movements.filter(m=>!date||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima'}).format(new Date(m.at))===date).map(m=><tr key={m.id}><th>{m.name??m.product_id}<small>{new Date(m.at).toLocaleString('es-PE',{timeZone:'America/Lima'})}</small></th><td>{m.reason}<small>{m.actor}</small></td><td className={m.delta<0?'negative':'positive'}>{m.delta>0?'+':''}{m.delta}</td><td><b>{m.remaining}</b></td></tr>)}</tbody></table></div>
  {data&&!data.movements.length&&<p className="helper">Los registros de stock inicial, pedidos y reposiciones aparecerán aquí.</p>}{more&&data&&<button className="secondary" onClick={()=>void load(true)}>Ver movimientos anteriores</button>}
  {draft&&<dialog ref={dialog} aria-label="Movimiento de gaseosas" onCancel={e=>{if(busy)e.preventDefault();else setDraft(null);}}><header className="dialog-head"><div><span className="eyebrow">INVENTARIO</span><h2>{draft.product.name}</h2></div><button className="icon-button" disabled={busy} aria-label="Cerrar inventario" onClick={()=>setDraft(null)}><X size={20}/></button></header><form onSubmit={e=>{e.preventDefault();void save();}}><div className="dialog-body"><p className="inventory-current">Disponible ahora: <strong>{data?.quantities[draft.product.id]??'Sin registrar'}</strong></p>{draft.type!=='initial'&&<label className="field"><span>Movimiento</span><select value={draft.type} disabled={busy} onChange={e=>setDraft({...draft,type:e.target.value,qty:''})}><option value="restock">Reposición · sumar unidades</option><option value="adjust">Ajuste · establecer saldo real</option></select></label>}<label className="field"><span>{draft.type==='restock'?'Unidades que ingresan':'Unidades disponibles'}</span><input autoFocus type="number" min={draft.type==='restock'?1:0} max="100000" step="1" required disabled={busy} value={draft.qty} onChange={e=>setDraft({...draft,qty:e.target.value})}/></label><label className="field"><span>Motivo / referencia</span><input required minLength={3} maxLength={500} disabled={busy} value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})} placeholder="Ej. Compra de una caja, conteo físico…"/></label>{error&&<p className="error-banner" role="alert">{error} {error.includes('cambió')&&<button type="button" onClick={()=>setDraft({...draft,revision:data!.revision,opId:crypto.randomUUID()})}>Usar stock actualizado y revisar</button>}</p>}</div><div className="dialog-foot"><button className="primary full" disabled={busy}>{busy?'Guardando…':'Guardar movimiento'}</button></div></form></dialog>}
 </section>;
}
