'use client';
import {useState,useEffect,useRef,type ReactNode,type FormEvent} from 'react';
import {LayoutGrid,ClipboardList,UtensilsCrossed,Wallet,ChartNoAxesCombined,History,Plus,Search,X,Check,ChefHat,Bell,RefreshCw,LogOut,ArrowDownLeft,ArrowUpRight,Minus,Clock,Receipt,CheckCheck} from 'lucide-react';
import {catalog,money,total,paid,served,balance,limaDate,type Day,type Order,type Line} from '@/lib/model';
import Reports from './reports';
import {Brand,Welcome} from './brand';
import {ServiceCard,OrdersBoard,TableMap,OrderForm,OrderDetail,PaymentForm,CloseForm,type OrderCallbacks} from './order-tools';
type State={lastPrices?:Day['prices'];day:Day|null;revision:number;days:{id:string;date:string;active:number|null}[]};
type Modal={type:string;order?:Order;table?:number;productId?:string;revision:number};
const clock=(s:string)=>new Date(s).toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit',timeZone:'America/Lima'});
const dateLabel=(s:string)=>new Date(s+'T12:00:00-05:00').toLocaleDateString('es-PE',{day:'numeric',month:'long',year:'numeric',timeZone:'America/Lima'});
const amount=(s:string)=>Math.round(Number(s)*100);
const amt=(c:number)=>(c/100).toFixed(2);
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function Dialog({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} className={wide?'dialog-wide':''} aria-label={title} onCancel={onClose}><header className="dialog-head"><div><span className="eyebrow">LUCIANOS · SERVICIO</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Cerrar"><X size={20}/></button></header>{children}</dialog>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><UtensilsCrossed size={30}/><h3>{title}</h3><p>{text}</p></div>}
export default function Workspace(){const [data,setData]=useState<State>({day:null,revision:0,days:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[view,setView]=useState('Mesas'),[reportRefresh,setReportRefresh]=useState(0),[modal,setModal]=useState<Modal|null>(null),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'),[toasts,setToasts]=useState<{id:string;text:string}[]>([]);const dataRef=useRef<State>({day:null,revision:0,days:[]}),loadSeq=useRef(0),mutationEpoch=useRef(0),busyRef=useRef(false),eventDay=useRef<string|null>(null);const pendingOperation=useRef<{key:string;opId:string;revision:number}|null>(null);const seen=useRef(new Set<string>()),initialized=useRef(false);const reportView=view==='Resumen'||view==='Historial';const day=data.day;const active=!!day&&!day.closed;
 function toast(text:string){const id=crypto.randomUUID();setToasts(s=>[...s,{id,text}].slice(-4));setTimeout(()=>setToasts(s=>s.filter(t=>t.id!==id)),8000)}
 function accept(s:State){
  const previous=dataRef.current;
  if(previous.day?.id===s.day?.id&&previous.revision>s.revision)return false;
  const operational={...s,day:s.day?.closed?null:s.day,revision:s.day?.closed?0:s.revision};dataRef.current=operational;setData(operational);
  for(const e of s.day?.events??[]){if(initialized.current&&eventDay.current===s.day?.id&&!seen.current.has(e.id))toast(e.text);seen.current.add(e.id)}
  eventDay.current=s.day?.id??null;initialized.current=true;return true;
 }
 async function load(id?:string){
  if(busyRef.current)return;
  const sequence=++loadSeq.current,epoch=mutationEpoch.current;
  try{const r=await fetch('/api/state'+(id?'?id='+id:''),{cache:'no-store'});const state:any=await r.json();
   if(sequence!==loadSeq.current||epoch!==mutationEpoch.current||busyRef.current)return;
   if(!r.ok)throw new Error(state.error);accept(state);setError('');
  }catch(e){if(sequence===loadSeq.current&&epoch===mutationEpoch.current)setError((e as Error).message)}
  finally{if(sequence===loadSeq.current)setLoading(false)}
 }
  useEffect(()=>{void load()},[]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[view]);
 useEffect(()=>{if(modal)return;const id=setInterval(()=>{void load()},12000);return()=>clearInterval(id)},[day?.id,modal]);
 async function send(a:any,keep=false){if(busyRef.current)return false;busyRef.current=true;mutationEpoch.current++;setBusy(true);const key=JSON.stringify({...a,dayId:day?.id});const operation=pendingOperation.current?.key===key?pendingOperation.current:{key,opId:crypto.randomUUID(),revision:modal?.revision??dataRef.current.revision};pendingOperation.current=operation;try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...a,dayId:day?.id,revision:operation.revision,opId:operation.opId})});const s:any=await r.json();if(!r.ok){if(r.status<500)pendingOperation.current=null;if(s.day){accept(s);setError('');if(a.type==='open'&&!s.day.closed)setModal(null)}throw new Error(s.error)}pendingOperation.current=null;accept(s);setError('');if(a.type==='close'){setView('Mesas');setQuery('');setFilter('Todos');toast('Jornada guardada en Historial. El salón está listo para una nueva jornada.');}if(keep&&modal)setModal({...modal,revision:s.revision,order:s.day.orders.find((o:Order)=>o.id===modal.order?.id)});else setModal(null);return true;}catch(e){toast((e as Error).message);return false}finally{busyRef.current=false;mutationEpoch.current++;setBusy(false)}}
 const open=(type:string,extra:Partial<Modal>={})=>setModal({type,revision:data.revision,...extra});
 const orders=day?.orders.filter(o=>!o.cancelled)??[];const pending=orders.filter(o=>paid(o)<total(o));const kitchen=orders.filter(o=>!served(o));const complete=orders.filter(o=>served(o)&&paid(o)===total(o));const cash=day?balance(day):0;const collected=orders.reduce((s,o)=>s+paid(o),0);const yape=orders.reduce((s,o)=>s+o.payments.reduce((p,x)=>p+x.yape,0),0);
 const navigate=(name:string)=>{setView(name);setFilter(name==='Pedidos'?'Por atender':'Todos');setQuery('')};
 const orderActions:OrderCallbacks={
  onOpen:o=>open('detail',{order:o}),onEdit:o=>open('order',{order:o}),onPay:o=>open('payment',{order:o}),
  onServe:(o,l,qty)=>{void send({type:'serve',orderId:o.id,lineId:l.id,qty},true)},
  onServeAll:o=>{void send({type:'serve-order',orderId:o.id},true)}
 };
 const renderOrder=(o:Order)=><ServiceCard key={o.id} order={o} active={active} busy={busy} {...orderActions}/>;
  if(loading)return <main className="loading"><Brand/><p>Cargando tu jornada…</p></main>;
 return <div className="app"><aside className="sidebar"><Brand/><nav aria-label="Navegación de Lucianos">{[{name:'Mesas',icon:LayoutGrid},{name:'Pedidos',icon:ClipboardList},{name:'Carta del día',icon:UtensilsCrossed},{name:'Caja',icon:Wallet},{name:'Resumen',icon:ChartNoAxesCombined},{name:'Historial',icon:History}].map(({name,icon:Icon},index)=><div className="nav-item" key={name}>{(index===0||index===4)&&<span className="nav-group-label">{index===0?'Servicio':'Consultas'}</span>}<button aria-label={name} aria-current={view===name?'page':undefined} className={view===name?'selected':''} onClick={()=>navigate(name)}><Icon size={20}/><span className="nav-label">{name}</span><span className="nav-mobile-label">{name==='Carta del día'?'Carta':name}</span>{name==='Pedidos'&&pending.length>0&&<span className="nav-count">{pending.length}</span>}</button></div>)}</nav><div className="sidebar-bottom"><div className="service-label"><span className={active?'dot':''}/>{active?'Jornada abierta':'Sin jornada abierta'}</div><strong>{day?.menu??'Elige tu carta'}</strong><small>{day?dateLabel(day.date):'Domingo · Lunes · Jueves'}</small><button className="sidebar-close" onClick={()=>active?open('close'):open('open')}><LogOut size={17}/>{active?'Cerrar jornada':'Abrir jornada'}</button><p>Buena cocina. Buen servicio.</p></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow breadcrumb">LUCIANOS <span>/</span> {view==='Mesas'?'SALÓN':view.toUpperCase()}</span><strong>{reportView?'Historial y reportes':day?dateLabel(day.date):'Bienvenido a Lucianos'}</strong></div><div className="top-actions"><button className={'service-status '+(active?'is-active':'is-idle')} onClick={()=>active?open('close'):open('open')} aria-label={active?'Ver cierre de jornada':'Abrir una jornada'}><span className="status-dot"/>{active?'En servicio · '+day.menu:'Preparar jornada'}</button><button className="icon-button" aria-label="Actualizar" onClick={()=>reportView?setReportRefresh(n=>n+1):void load()}><RefreshCw size={18}/></button><button className="icon-button" aria-label="Ver avisos" onClick={()=>open('events')}><Bell size={20}/>{day?.events.length? <span className="bell-dot"/>:null}</button><span className="avatar">L</span></div></header><div className="content">{error&&<div className="error-banner">{error} <button onClick={()=>void load(day?.id)}>Reintentar</button>{error.includes('sesión')&&<a href="/signin-with-chatgpt?return_to=/" target="_top">Iniciar sesión</a>}</div>}
 {reportView?<Reports key={view} initialTab={view==='Historial'?'Jornadas':'Resumen'} refresh={reportRefresh}/>:(!day&&view!=='Mesas'?<section className="welcome"><span className="eyebrow">{view.toUpperCase()}</span><h1>{view==='Pedidos'?'Pedidos del salón':view==='Caja'?'Caja del día':view==='Resumen'?'Resumen de ventas':'Carta del día'}</h1><Empty title={error?'Los registros no están disponibles':'Todavía no hay una jornada'} text={error?'Pulsa Reintentar para recuperar los registros.':view==='Pedidos'?'Abre una jornada para registrar y atender pedidos.':view==='Caja'?'Abre una jornada para registrar la caja inicial, los cobros y movimientos.':view==='Resumen'?'Las ventas y los gráficos aparecerán cuando registres pedidos.':'Elige Domingo, Lunes o Jueves al abrir la jornada.'}/><button className="primary" style={{marginTop:24}} disabled={!!error} onClick={()=>open('open')}><Plus size={20}/>Abrir jornada</button></section>:!day?<Welcome onOpen={menu=>open('open',{productId:menu})} onHistory={()=>navigate('Historial')}/>:<><div className="page-heading"><div><span className="eyebrow">{day.menu.toUpperCase()} · {day.closed?'JORNADA CERRADA':'EN SERVICIO'}</span><h1>{view==='Mesas'?'El salón.':view==='Pedidos'?'Pedidos en marcha.':view==='Carta del día'?'La carta de hoy.':view==='Caja'?'Tu caja, al día.':'Así va tu jornada.'}</h1><p>{view==='Mesas'?'Mesa libre, plato servido, cuenta pendiente. Todo a la vista.':view==='Pedidos'?'Atención y pagos, sin perder ningún detalle.':view==='Carta del día'?'Precios y disponibilidad para el servicio.':view==='Caja'?'Cada ingreso, salida y vuelto queda registrado.':'Ventas, platos y bebidas de esta jornada.'}</p></div>{active?<button className="primary" onClick={()=>open('order')}><Plus size={20}/>Nuevo pedido</button>:<button className="primary" onClick={()=>open('open')}><Plus size={20}/>Abrir jornada</button>}</div>
 <div className="stats" aria-live="polite"><div><span><Receipt size={17}/>Cobrado</span><strong>{money(collected)}</strong><small>{orders.filter(o=>paid(o)===total(o)).length} pedidos pagados</small></div><div><span><Wallet size={17}/>Por cobrar</span><strong>{money(orders.reduce((n,o)=>n+total(o)-paid(o),0))}</strong><small>{pending.length} pedidos con saldo</small></div><div><span><ChefHat size={17}/>Por servir</span><strong>{kitchen.reduce((n,o)=>n+o.lines.reduce((s,l)=>s+l.qty-l.served,0),0)}<em> productos</em></strong><small>{kitchen.length} pedidos pendientes de atención</small></div><div className="cash-kpi"><span><Wallet size={17}/>Efectivo en caja</span><strong>{money(cash)}</strong><small>Inicial {money(day.opening)} · Yape aparte {money(yape)}</small></div></div>
  {view==='Mesas'&&<TableMap day={day} active={active} busy={busy} onNew={table=>open('order',{table})} onTable={table=>open('table',{table})} onServeAll={orderActions.onServeAll}/>} 
  {view==='Pedidos'&&<OrdersBoard orders={orders} filter={filter} onFilter={setFilter} query={query} onQuery={setQuery} active={active} busy={busy} {...orderActions}/>} 
  {view==='Carta del día'&&<><div className="filters">{['Todos','Platos','Bebidas','Adicionales'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}<label className="search"><Search size={18}/><input placeholder="Buscar en la carta" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="catalog-grid">{catalog.filter(p=>p.days.includes(day.menu)&&(filter==='Todos'||p.category===filter)&&normalize(p.name).includes(normalize(query))).map(p=><article key={p.id} className="product-card"><span className="eyebrow">{p.category}</span><h3>{p.name}</h3><div className="product-bottom"><button disabled={!active} onClick={()=>open('price',{productId:p.id})} className="price">{money(day.prices[p.id])}<small>Editar precio</small></button><button disabled={!active||day.stock[p.id]===null} className={'stock-pill '+(day.stock[p.id]===0?'out':'')} onClick={()=>open('stock',{productId:p.id})}>{day.stock[p.id]===null?'Sin límite':day.stock[p.id]===0?'Agotado':day.stock[p.id]+' disponibles'}</button></div></article>)}</div><p className="helper">El precio de la carta se usa en nuevos pedidos. Puedes ajustar el precio de cada producto dentro de un pedido.</p></>}
 {view==='Caja'&&<><div className="cash-summary"><div><span className="eyebrow">EFECTIVO ESPERADO EN CAJA</span><strong>{money(cash)}</strong><span>Inicio {money(day.opening)} · Cobros en efectivo {money(orders.reduce((n,o)=>n+o.payments.reduce((s,p)=>s+p.cash,0),0))}</span></div><div><span className="eyebrow">YAPE RECIBIDO</span><strong>{money(yape)}</strong><span>Registrado manualmente al cobrar</span></div>{active&&<button className="primary light" onClick={()=>open('movement')}><Plus size={19}/>Registrar movimiento</button>}</div><div className="section-heading"><h2>Movimientos de caja</h2><span>Incluye cobros y vueltos</span></div><div className="ledger"><div className="ledger-row head"><span>Hora / motivo</span><span>Recibido</span><span>Vuelto</span><span>Efectivo neto</span></div>{[{id:'opening',at:day.opened,reason:'Apertura de caja',net:day.opening,tender:day.opening,change:0},...day.movements.map(m=>({id:m.id,at:m.at,reason:m.reason,net:m.amount,tender:m.amount,change:0})),...orders.flatMap(o=>o.payments.filter(p=>p.cash>0||p.change>0).map(p=>({id:p.id,at:p.at,reason:'Cobro · Pedido #'+o.number+' · Mesa '+o.table,net:p.cash,tender:p.tender,change:p.change})))].sort((a,b)=>b.at.localeCompare(a.at)).map(m=><div className="ledger-row" key={m.id}><span><strong>{m.reason}</strong><small>{clock(m.at)}</small></span><span>{money(m.tender)}</span><span>{m.change?money(m.change):'—'}</span><b className={m.net<0?'negative':'positive'}>{m.net>0?'+':''}{money(m.net)}</b></div>)}</div>{day.closed&&<div className="closing-note"><CheckCheck size={22}/><span>Jornada cerrada · Efectivo contado: <strong>{money(day.counted??0)}</strong> · Diferencia: <strong>{money((day.counted??0)-cash)}</strong></span></div>}</>}
 </>)}</div><footer><strong>Lucianos</strong><span>Cocina criolla, hecha en casa.</span><span>Soles peruanos · Hora de Lima</span></footer></main>
 {modal&&<Dialog wide={['close','order','table'].includes(modal.type)} title={modal.type==='open'?'Abrir jornada':modal.type==='order'?(modal.order?'Editar pedido #'+modal.order.number:'Nuevo pedido'):modal.type==='detail'?'Pedido #'+modal.order?.number:modal.type==='table'?'Mesa '+modal.table:modal.type==='payment'?'Registrar pago':modal.type==='movement'?'Movimiento de caja':modal.type==='close'?'Cerrar jornada':modal.type==='events'?'Avisos de la jornada':modal.type==='price'?'Editar precio de carta':'Ajustar disponibilidad'} onClose={()=>!busy&&setModal(null)}>
 {modal.type==='open'&&<OpenForm busy={busy} initial={modal.productId} prices={data.lastPrices} onSave={a=>send(a)}/>}
 {modal.type==='order'&&day&&<OrderForm day={day} order={modal.order} initialTable={modal.table} busy={busy} onSave={a=>send(a)}/>}
 {modal.type==='table'&&<div className="dialog-body"><div className="order-grid service-grid">{orders.filter(o=>o.table===modal.table&&(!served(o)||paid(o)<total(o))).map(renderOrder)}</div>{active&&<button className="primary full" style={{marginTop:20}} onClick={()=>open('order',{table:modal.table})}><Plus size={18}/>Agregar pedido a esta mesa</button>}</div>} 
  {modal.type==='detail'&&modal.order&&<OrderDetail order={day?.orders.find(o=>o.id===modal.order?.id)??modal.order} active={active} busy={busy} {...orderActions} onCancel={()=>{if(window.confirm('¿Anular el pedido #'+modal.order!.number+' y devolver su disponibilidad?'))void send({type:'cancel',orderId:modal.order!.id})}}/>} 
  {modal.type==='payment'&&modal.order&&day&&<PaymentForm order={modal.order} day={day} busy={busy} onSave={a=>send(a)}/>}
 {modal.type==='movement'&&<MovementForm busy={busy} onSave={a=>send(a)}/>}
 {(modal.type==='price'||modal.type==='stock')&&day&&<AdjustForm type={modal.type} day={day} productId={modal.productId!} busy={busy} onSave={a=>send(a)}/>}
 {modal.type==='close'&&day&&<CloseForm day={day} busy={busy} onSave={a=>send(a)}/>}
 {modal.type==='events'&&<div className="dialog-body notifications">{day?.events.map(e=><div key={e.id}><Bell size={17}/><p>{e.text}<small>{clock(e.at)}</small></p></div>)}{!day?.events.length&&<p>No hay avisos todavía.</p>}</div>}
 </Dialog>}
 <div className="toasts" role="status" aria-live="polite">{toasts.map(t=><div className="toast" key={t.id}><Bell size={20}/><p>{t.text}</p><button onClick={()=>setToasts(s=>s.filter(x=>x.id!==t.id))} aria-label="Descartar aviso"><X size={16}/></button></div>)}</div></div>;
}
function OpenForm({busy,initial,prices,onSave}:{busy:boolean;initial?:string;prices?:Day['prices'];onSave:(a:any)=>Promise<boolean>}){const [menu,setMenu]=useState(initial??'Domingo'),[date,setDate]=useState(limaDate()),[opening,setOpening]=useState(''),[stock,setStock]=useState<Record<string,string>>({});const products=catalog.filter(p=>p.days.includes(menu));return <form onSubmit={e=>{e.preventDefault();void onSave({type:'open',menu,date,opening:amount(opening),stock:Object.fromEntries(products.map(p=>[p.id,p.category==='Platos'?Number(stock[p.id]??0):stock[p.id]?Number(stock[p.id]):null])),prices})}}><div className="dialog-body"><p className="helper">Elige la carta y registra lo disponible antes de recibir pedidos.</p><div className="day-options">{['Domingo','Lunes','Jueves'].map(d=><button type="button" className={menu===d?'chosen':''} key={d} onClick={()=>setMenu(d)}><UtensilsCrossed size={22}/>{d}</button>)}</div><div className="form-columns"><Field label="Fecha de la jornada"><input type="date" value={date} max={limaDate()} required onChange={e=>setDate(e.target.value)}/></Field><Field label="Efectivo inicial en caja (S/)"><input type="number" min="0" step="0.01" required value={opening} onChange={e=>setOpening(e.target.value)} placeholder="0.00"/></Field></div><h3>Platos disponibles</h3><p className="helper">Ingresa 0 si un plato no estará disponible.</p><div className="stock-inputs">{products.filter(p=>p.category==='Platos').map(p=><Field label={p.name} key={p.id}><input aria-label={'Cantidad inicial de '+p.name} type="number" required min="0" step="1" max="100000" value={stock[p.id]??''} onChange={e=>setStock({...stock,[p.id]:e.target.value})} placeholder="0"/></Field>)}</div><details><summary>Disponibilidad de bebidas y adicionales</summary><p className="helper">Deja vacío para vender sin límite. Ingresa 0 para marcar agotado.</p><div className="stock-inputs">{products.filter(p=>p.category!=='Platos').map(p=><Field key={p.id} label={p.name}><input type="number" min="0" step="1" value={stock[p.id]??''} placeholder="Sin límite" onChange={e=>setStock({...stock,[p.id]:e.target.value})}/></Field>)}</div></details></div><div className="dialog-foot"><button className="primary full" disabled={busy}>{busy?'Guardando…':'Abrir jornada'}</button></div></form>}

 function MovementForm({busy,onSave}:{busy:boolean;onSave:(a:any)=>Promise<boolean>}){const [direction,setDirection]=useState('out'),[value,setValue]=useState(''),[reason,setReason]=useState('');return <form onSubmit={e=>{e.preventDefault();void onSave({type:'movement',direction,amount:amount(value),reason})}}><div className="dialog-body"><Field label="Tipo de movimiento"><select value={direction} onChange={e=>setDirection(e.target.value)}><option value="out">Salida de efectivo</option><option value="in">Ingreso de efectivo</option></select></Field><Field label="Monto (S/)"><input type="number" min="0.01" step="0.01" required value={value} onChange={e=>setValue(e.target.value)}/></Field><Field label="Motivo"><textarea required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ej. Compra de hielo, retiro para sencillo…"/></Field><p className="helper">El vuelto al cliente ya se registra al cobrar. Registra aquí movimientos adicionales de caja.</p></div><div className="dialog-foot"><button className="primary full" disabled={busy}>Guardar movimiento</button></div></form>}
function AdjustForm({type,day,productId,busy,onSave}:{type:string;day:Day;productId:string;busy:boolean;onSave:(a:any)=>Promise<boolean>}){const p=catalog.find(p=>p.id===productId)!;const [value,setValue]=useState(type==='price'?amt(day.prices[productId]):String(day.stock[productId]));return <form onSubmit={e=>{e.preventDefault();void onSave(type==='price'?{type,productId,price:amount(value)}:{type,productId,qty:Number(value)})}}><div className="dialog-body"><h3>{p.name}</h3><Field label={type==='price'?'Nuevo precio (S/)':'Cantidad disponible ahora'}><input type="number" required min="0" step={type==='price'?'0.01':'1'} value={value} onChange={e=>setValue(e.target.value)}/></Field><p className="helper">{type==='price'?'Se aplicará a los próximos pedidos. Los precios de pedidos existentes se conservan.':'Ingresa lo que queda disponible, sin incluir los productos ya registrados en pedidos.'}</p></div><div className="dialog-foot"><button className="primary full" disabled={busy}>Guardar ajuste</button></div></form>}
