export type Product={id:string;name:string;category:'Platos'|'Bebidas'|'Adicionales';price:number;days:string[]};
const all=['Domingo','Lunes','Jueves'];
const p=(id:string,name:string,price:number,days=all,category:Product['category']='Platos'):Product=>({id,name,price:price*100,days,category});
export const catalog:Product[]=[p('patita','Patita en fiambre',18),p('pato','Pato guisado',30,['Domingo']),p('cabrito','Cabrito',30,['Domingo']),p('cuy','Cuy frito',30,['Domingo']),p('lomo','Lomo saltado',28,['Domingo']),p('aji','Ají de gallina',15,['Domingo']),p('bisteck','Bisteck a lo pobre',28,['Domingo']),p('verdes-churrasco','Tallarines verdes con churrasco',18,['Domingo']),p('verdes-pollo','Tallarines verdes con pollo a la plancha',18,['Domingo']),p('pollo','Pollo a la plancha',22,['Domingo']),p('pepian','Pepián de gallina',18,['Domingo']),p('churrasco','Churrasco',22,['Domingo']),p('shambar','Shámbar',18,['Lunes']),p('patasquita','Patasquita',18,['Jueves']),p('coca-litro','Coca-Cola · 1 litro',7,all,'Bebidas'),p('inca-litro','Inca Kola · 1 litro',7,all,'Bebidas'),p('coca-personal','Coca-Cola · personal',3,all,'Bebidas'),p('inca-personal','Inca Kola · personal',3,all,'Bebidas'),p('inca-gordita','Inca Kola · gordita',5,all,'Bebidas'),p('maracuya','Maracuyá · jarra de 1 litro',14,['Domingo'],'Bebidas'),p('limonada','Limonada · jarra de 1 litro',12,['Domingo'],'Bebidas'),p('chicha','Chicha morada · jarra',14,['Domingo'],'Bebidas'),p('trujillo','Cerveza Trujillo',10,all,'Bebidas'),p('cusquena','Cusqueña negra',12,all,'Bebidas'),p('taper','Táper',2,all,'Adicionales')];
export type Line={id:string;productId:string;name:string;category:Product['category'];qty:number;price:number;served:number;notes?:string};
export type Payment={id:string;cash:number;yape:number;tender:number;change:number;at:string;cashAfter?:number};
export type Order={id:string;number:number;table:number;at:string;notes:string;lines:Line[];payments:Payment[];cancelled:boolean};
export type Movement={id:string;amount:number;reason:string;at:string};
export const dayCatalog=(d:Day):Product[]=>d.catalog??catalog.filter(p=>Object.hasOwn(d.prices,p.id));
export type Day={catalog?:Product[];id:string;date:string;menu:string;opened:string;closed:string|null;opening:number;counted:number|null;stock:Record<string,number|null>;initial:Record<string,number|null>;prices:Record<string,number>;orders:Order[];movements:Movement[];events:{id:string;text:string;at:string}[];actions:string[]};
export const money=(n:number)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(n/100);
export const total=(o:Order)=>o.lines.reduce((n,l)=>n+l.qty*l.price,0);
export const paid=(o:Order)=>o.payments.reduce((n,p)=>n+p.cash+p.yape,0);
export const served=(o:Order)=>o.lines.every(l=>l.served===l.qty);
export const balance=(d:Day)=>d.opening+d.orders.reduce((n,o)=>n+o.payments.reduce((s,p)=>s+p.cash,0),0)+d.movements.reduce((n,m)=>n+m.amount,0);
export const limaDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function check(ok:unknown,msg:string):asserts ok {if(!ok)throw new Error(msg)}
function integer(n:unknown,min=0,max=100000000):asserts n is number {check(typeof n==='number'&&Number.isSafeInteger(n)&&n>=min&&n<=max,'Ingresa un monto o cantidad válido.');}
function event(d:Day,text:string){d.events.unshift({id:crypto.randomUUID(),text,at:new Date().toISOString()});}
export function openDay(a:any,products:Product[]=catalog):Day {check(all.includes(a.menu),'Selecciona una carta válida.');check(/^\d{4}-\d{2}-\d{2}$/.test(a.date)&&a.date<=limaDate(),'La fecha no puede estar en el futuro.');integer(a.opening);const stock:Day['stock']={},prices:Day['prices']={};for(const p of products.filter(p=>p.days.includes(a.menu))){const q=a.stock?.[p.id];check(q===null&&p.category!=='Platos'||typeof q==='number','Registra las cantidades de platos.');if(q!==null)integer(q,0,100000);stock[p.id]=q;const price=a.prices?.[p.id]??p.price;integer(price);prices[p.id]=price;}const d:Day={catalog:structuredClone(products.filter(p=>p.days.includes(a.menu))),id:crypto.randomUUID(),date:a.date,menu:a.menu,opened:new Date().toISOString(),closed:null,opening:a.opening,counted:null,stock,initial:{...stock},prices,orders:[],movements:[],events:[],actions:[]};event(d,'Jornada abierta. Caja inicial: '+money(d.opening));return d;}
export function applyAction(original:Day,a:any):Day {check(typeof a.opId==='string'&&a.opId.length<100,'Operación inválida.');if(original.actions.includes(a.opId))return original;check(!original.closed,'Esta jornada ya está cerrada.');const d:Day=structuredClone(original);const products=dayCatalog(d);const at=new Date().toISOString();const o=d.orders.find(o=>o.id===a.orderId);
 if(a.type==='order'){
  if(o)check(!o.cancelled,'Pedido anulado.');
  integer(a.table,1,13);check(Array.isArray(a.lines)&&a.lines.length>0&&a.lines.length<=100,'Agrega productos al pedido.');check(typeof a.notes==='string'&&a.notes.length<=2000,'Los detalles son demasiado largos.');
  const lines:Line[]=a.lines.map((l:any)=>{const p=products.find(p=>p.id===l.productId&&p.days.includes(d.menu));check(p,'El producto no pertenece a esta carta.');integer(l.qty,1,1000);integer(l.price);check(l.notes===undefined||typeof l.notes==='string'&&l.notes.length<=1000,'El detalle por plato debe tener como máximo 1000 caracteres.');const old=o?.lines.find(x=>x.id===l.id);if(old)check(old.productId===p.id,'Producto inválido.');check((old?.served??0)<=l.qty,'No se pueden quitar platos ya entregados.');return {id:old?.id??crypto.randomUUID(),productId:p.id,name:old?.name??p.name,category:old?.category??p.category,qty:l.qty,price:l.price,served:old?.served??0,notes:(l.notes??old?.notes??'').trim()};});
  if(o&&paid(o)===total(o))for(const old of o.lines){const next=lines.find(l=>l.id===old.id);check(next&&next.qty>=old.qty&&next.price===old.price,'Conserva los productos y precios ya pagados. Puedes agregar más productos.');}
  check(new Set(lines.map(l=>l.id)).size===lines.length,'Hay líneas repetidas.');if(o)for(const l of o.lines)check(l.served===0||lines.some(n=>n.id===l.id),'No se pueden quitar platos ya entregados.');
  const before:Record<string,number>={},after:Record<string,number>={};for(const l of o?.lines??[])before[l.productId]=(before[l.productId]??0)+l.qty;for(const l of lines)after[l.productId]=(after[l.productId]??0)+l.qty;
  for(const id of new Set([...Object.keys(before),...Object.keys(after)])){const delta=(after[id]??0)-(before[id]??0);if(d.stock[id]!==null){check(d.stock[id]>=delta,'No hay suficiente disponibilidad de '+products.find(p=>p.id===id)?.name);d.stock[id]-=delta;if(d.stock[id]===0&&delta>0)event(d,'Se agotó: '+products.find(p=>p.id===id)?.name);}}
  const next:Order={id:o?.id??crypto.randomUUID(),number:o?.number??d.orders.length+1,table:a.table,at:o?.at??at,notes:a.notes,lines,payments:o?.payments??[],cancelled:false};check(total(next)>0,'El total del pedido debe ser mayor que cero.');check(paid(next)<=total(next),'El total no puede ser menor al monto pagado.');if(o)d.orders[d.orders.indexOf(o)]=next;else d.orders.push(next);event(d,(o?'Pedido actualizado':'Nuevo pedido')+' #'+next.number+' · Mesa '+next.table);
 }else if(a.type==='serve'){check(o&&!o.cancelled,'Pedido no disponible.');const l=o.lines.find(l=>l.id===a.lineId);check(l,'Plato no disponible.');integer(a.qty,0,l.qty);l.served=a.qty;event(d,(served(o)?'Pedido atendido':'Entrega actualizada')+' · Pedido #'+o.number+(served(o)&&paid(o)<total(o)?' · Por pagar':''));
 }else if(a.type==='serve-order'){check(o&&!o.cancelled,'Pedido no disponible.');for(const l of o.lines)l.served=l.qty;event(d,'Pedido atendido #'+o.number+' · '+(paid(o)===total(o)?'Pagado':'Por pagar'));
 }else if(a.type==='payment'){check(o&&!o.cancelled,'Pedido no disponible.');integer(a.cash);integer(a.yape);integer(a.tender);check(a.cash+a.yape>0&&a.cash+a.yape<=total(o)-paid(o),'El pago debe ser mayor a cero y no superar el saldo pendiente.');check(a.tender>=a.cash,'El efectivo recibido no alcanza para cubrir el pago.');const cashAfter=balance(d)+a.cash;check(cashAfter>=0,'Saldo de caja inválido.');o.payments.push({id:crypto.randomUUID(),cash:a.cash,yape:a.yape,tender:a.tender,change:a.tender-a.cash,at,cashAfter});event(d,'Pago registrado · Pedido #'+o.number+' · Efectivo '+money(a.cash)+' · Yape '+money(a.yape)+(a.tender>a.cash?' · Vuelto '+money(a.tender-a.cash):'')+' · Caja actual '+money(cashAfter));
 }else if(a.type==='movement'){integer(a.amount,1);check(a.direction==='in'||a.direction==='out','Movimiento inválido.');check(typeof a.reason==='string'&&a.reason.trim().length>=3&&a.reason.length<=500,'Escribe el motivo del movimiento.');const amount=a.direction==='in'?a.amount:-a.amount;check(balance(d)+amount>=0,'El retiro supera el efectivo disponible.');d.movements.push({id:crypto.randomUUID(),amount,reason:a.reason.trim(),at});event(d,(amount>0?'Ingreso':'Salida')+' de caja: '+money(Math.abs(amount))+' · '+a.reason.trim());
 }else if(a.type==='stock'){check(Object.hasOwn(d.stock,a.productId),'Producto no disponible.');integer(a.qty,0,100000);const prev=d.stock[a.productId];check(prev!==null,'Este producto no tiene límite de existencias.');d.stock[a.productId]=a.qty;d.initial[a.productId]=(d.initial[a.productId]??0)+a.qty-prev;event(d,'Disponibilidad actualizada: '+products.find(p=>p.id===a.productId)?.name+' · '+a.qty+' disponibles');
 }else if(a.type==='price'){check(Object.hasOwn(d.prices,a.productId),'Producto no disponible.');integer(a.price);d.prices[a.productId]=a.price;event(d,'Precio de carta actualizado: '+products.find(p=>p.id===a.productId)?.name+' · '+money(a.price));
 }else if(a.type==='cancel'){check(o&&!o.cancelled,'Pedido no disponible.');check(paid(o)===0&&o.lines.every(l=>l.served===0),'Solo se puede anular un pedido sin pagos ni entregas.');o.cancelled=true;for(const l of o.lines)if(d.stock[l.productId]!==null)d.stock[l.productId]!+=l.qty;event(d,'Pedido anulado #'+o.number+' · Disponibilidad devuelta');
 }else if(a.type==='close'){check(!d.orders.some(o=>!o.cancelled&&(!served(o)||paid(o)<total(o))),'Atiende y cobra todos los pedidos antes de cerrar.');integer(a.counted);d.counted=a.counted;d.closed=at;event(d,'Jornada cerrada · Diferencia de caja '+money(a.counted-balance(d)));
 }else throw new Error('Operación no reconocida.');d.actions.push(a.opId);return d;}
