'use client';
import {useEffect,useRef,useState} from 'react';
import {Brand} from '@/app/brand';
export default function AccessForm(){
 const [token,setToken]=useState(''),[type,setType]=useState('forgot'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[enabled,setEnabled]=useState<boolean|null>(null);const lock=useRef(false);
 useEffect(()=>{const params=new URLSearchParams(window.location.hash.slice(1));const value=params.get('token');if(value){setToken(value);setType(params.get('type')==='verify'?'verify':'reset');window.history.replaceState(null,'',window.location.pathname);}void fetch('/api/auth/email',{cache:'no-store'}).then(r=>r.json()).then((d:any)=>setEnabled(d.emailEnabled)).catch(()=>setError('No se pudo consultar el servicio de correo.'));},[]);
 async function submit(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await fetch('/api/auth/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(type==='verify'?{type:'confirm',token}:type==='reset'?{type:'reset',token,password,confirmation}:{type:'forgot',username})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setMessage(d.message);if(type!=='forgot'){setToken('');setPassword('');setConfirmation('');}}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 return <main className="login-screen"><section className="login-card"><Brand/><div className="login-title"><span className="eyebrow">TU ACCESO A LUCIANOS</span><h1>{type==='verify'?'Verifica tu correo.':type==='reset'?'Nueva contraseña.':'Recuperar acceso.'}</h1><p>{type==='verify'?'Confirma el correo para poder recuperar tu cuenta.':type==='reset'?'Elige la contraseña que usarás para entrar.':'Ingresa tu usuario para solicitar un enlace de recuperación.'}</p></div>
  {message?<p className="account-success" role="status">{message}</p>:<form onSubmit={e=>{e.preventDefault();void submit();}}>{type==='forgot'?<><label htmlFor="recover-username">Usuario de Lucianos</label><input id="recover-username" required maxLength={120} autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/>{enabled===false&&<p className="email-pending">El envío de correos aún no está configurado. Solicita al administrador que restablezca tu contraseña desde «Usuarios».</p>}</>:type==='reset'?<><label htmlFor="recover-password">Nueva contraseña</label><input id="recover-password" type="password" autoComplete="new-password" required minLength={8} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/><label htmlFor="recover-confirm">Confirmar nueva contraseña</label><input id="recover-confirm" type="password" autoComplete="new-password" required minLength={8} maxLength={256} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></>:null}<div className="login-error" role="alert">{error}</div><button className="login-submit" disabled={busy||(type==='forgot'?!enabled:!token)}>{busy?'Procesando…':type==='verify'?'Confirmar mi correo':type==='reset'?'Guardar contraseña':'Enviar enlace de recuperación'}</button></form>}
  <a className="account-back" href="/login">Volver a iniciar sesión</a>
 </section></main>;
}
